name: List Files

on:
  push:
    branches: [ master ]


jobs:
  list-files:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: List directory contents
      run: ls -la