name: List Files

on:
  push:
    branches: [ master ]


jobs:
  list-files:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: fold1
    
    steps:
    - name: List files before checkout
      run: ls -la
    - uses: actions/checkout@v3
    - name: List files after checkout
      working-directory: ./website
      run: ls -la
